<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1 

- Subsetting: To select a portion of the data from the list and away 
- Indexing: To select a single item from the list/array 
- Slicing: To take a range of data from the list/array 
- Masking: _A feature that allows you to show values in a numpy array based on whether they are true or false for a particular condition_

# Exercise 2 

In [80]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])


import numpy as np 

np_array_2d[:,0] # subset all first elements
array_integer = np_array_2d[:,0].astype(int) 
remainder_array = array_integer%2
#print(remainder_array)
#Create a mask that checks if the remainder is 0 or not. If remainder = 1(odd), return True, else return False (even)
odd_mask = remainder_array == 1 
print(odd_mask)

[ True  True False False  True  True False False False  True]


In [102]:
np_array_2d[odd_mask,1] #index elements that are odd, AND return the alphabet in index 1

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

# Exercise 3

In [153]:
import numpy as np 

numbers_2d_array = np.array ([[66, 50, 57, -1, -1],
                              [92, -1, 88, -1, -1],
                              [75, -1, -1, 76, -1],
                              [-1, 51, 87, -1, -1],
                              [71, -1, 67, -1, 69]])
integer_2d_array = numbers_2d_array.astype(int)
print(integer_2d_array)

[[66 50 57 -1 -1]
 [92 -1 88 -1 -1]
 [75 -1 -1 76 -1]
 [-1 51 87 -1 -1]
 [71 -1 67 -1 69]]


In [154]:
#mask numbers accordingly 
integer_2d_array[integer_2d_array <50] = -1 
integer_2d_array[integer_2d_array >50] = +1 
integer_2d_array[integer_2d_array ==50] = 0

In [155]:
print(integer_2d_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
