<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

In [1]:
import numpy as np

py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
#x = np_array

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

## 1.2 Arrays only | Subsetting by masking

In [3]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask
np_array[my_mask] #ask python to show numbers that are true aka > 3 (4 and above)

array([ 4,  5,  6,  7,  8,  9, 10])

In [4]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [5]:
np_array[~(np_array > 3)]  #invert the mask 

array([1, 2, 3])

In [6]:
np_array[(np_array > 3) & (np_array < 8)]

array([4, 5, 6, 7])

In [7]:
np_array[(np_array < 3) | (np_array > 8)] #combine one mask OR another mask if true 

array([ 1,  2,  9, 10])

Always use bitwise NOT(~), Bitwise OR (|) and Bitwise AND (&) when comibining masks with numpy 

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [10]:
import numpy as np
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [15]:

#What is at position 4 (index 3)? 

print(py_list_2d[3])
print(np_array_2d[3])

[4, 'D']
['4' 'D']


In [17]:
# What is the FIRST element at position 4(index 3)?

py_list_2d[3][0]

4

In [21]:
np_array_2d[3,0]

np.str_('4')

In [22]:
# Fist 3 elements 

py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [24]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [33]:
py_list_2d[:3][0] #only gives the first of the list 

#:3 means index from 0 to 3 

[1, 'A']

In [32]:
np_array_2d[:3,0]

array(['1', '2', '3'], dtype='<U21')

In [25]:
py_list_2d[3:6][0]

[4, 'D']

In [40]:
np_array_2d[3:6,0] # ',' means slice 

array(['4', '5', '6'], dtype='<U21')

In [41]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

In [42]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [45]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [47]:
x=[1]
x+=[2]
x+=[3]
x+=[4]
x

[1, 2, 3, 4]

In [50]:
# this has faster execution speed 

x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

# Some loose ends

## 1.5 Tuples

Tuples are similar to list, but they use ( ) and cannot be changed after creation i.e they are immutable 

In [53]:
a = (1,2,3)
print(a[0])

1


In [55]:
# the following will not work 

# a[0]=-1
# a[0]+=[10]

## 1.6 Be VERY careful when copying

In [ ]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [ ]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

## Footnotes