<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

In [3]:
list = [1,2,3,4,5] #list() is a function aka a keyword. Hence, dont confuse using this with a variable 

In [15]:
import numpy as np 

In [16]:
py_list=[1,2,3,4,5] #good for data presentation 

In [17]:
py_list

[1, 2, 3, 4, 5]

In [18]:
np_array = np.array([1,2,3,4,5])
np_array #used for mathematical scienfitic stuff. good for long lists of number

array([1, 2, 3, 4, 5])

### Things you can do or not

In [24]:
import numpy as np
py_list = [1,2,3,4,5]
np_array = np.array([1,2,3,4,5])

In [26]:
py_list + 1

TypeError: can only concatenate list (not "int") to list

In [27]:
np_array +1 #can add/multiply 

array([2, 3, 4, 5, 6])

In [28]:
np_array**2

array([ 1,  4,  9, 16, 25])

In [29]:
py_list*2 #py_list remains unchanged. *2 will only show 2 of pylist 

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [30]:
#find length of array 

len(np_array)
len(py_list)

5

In [31]:
my_rand_numbers= np.random.randint(0,100,100)

In [34]:
mask = (my_rand_numbers < 50) #shows true/false based on conditon fulfilled

In [33]:
my_rand_numbers[mask] #this will give all the trues that are < 50 

array([32,  8, 47,  6, 26, 21, 31, 14, 48, 16, 21, 12, 43, 39, 49, 21, 46,
       31, 36, 27,  3, 49, 35,  0, 38, 12, 43, 48, 44, 14,  0,  8, 11,  1,
       11, 34,  0,  0, 48,  0, 41,  9, 43, 41, 37, 49,  6, 29,  0,  5, 47,
       32,  6, 36, 41,  5, 42, 43])

In [35]:
mask = (my_rand_numbers < 50) & (my_rand_numbers%2==1)
#shows true/false based on conditon fulfilled 
# if divide by 2 = 0, number is even. Else, odd

In [36]:
my_rand_numbers[mask]

array([47, 21, 31, 21, 43, 39, 49, 21, 31, 27,  3, 49, 35, 43, 11,  1, 11,
       41,  9, 43, 41, 37, 49, 29,  5, 47, 41,  5, 43])

In [37]:
mask = (my_rand_numbers < 50) | (my_rand_numbers%2==1)
# shows true/false based on conditon fulfilled 
# vertical line is OR. Thus, this gives more numbers since more condition more fulfilled 
# if divide by 2 = 0, number is even. Else, odd
my_rand_numbers[mask]

array([32,  8, 47,  6, 26, 21, 53, 31, 14, 87, 93, 48, 16, 21, 63, 12, 43,
       39, 49, 21, 46, 63, 31, 36, 27, 57,  3, 49, 35,  0, 63, 38, 67, 12,
       43, 48, 79, 91, 44, 81, 14,  0,  8, 51, 11, 87,  1, 11, 34, 57, 93,
        0,  0, 48,  0, 97, 63, 41,  9, 43, 41, 37, 49, 89,  6, 29, 63,  0,
        5, 47, 65, 75, 32,  6, 36, 91, 41,  5, 42, 51, 43])

In [38]:
my_rand_numbers[0] 
#this is to access the first number in the array 
#why use square bracket? this is used to index to subset a value in the array  

np.int64(32)

In [39]:
my_rand_numbers[-1]
#this shows the last value of the array and so on. eg. if use -2(45)

np.int64(43)

In [40]:
py_list[-2]

4

In [41]:
py_2d_list = [[1,2,3],[4,5,6],[7,8,9]]

In [42]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [67]:
np_array_2d

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

In [66]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

## NP array vs Py list? 

- NP array dont tolerate multiple variable type. Only allows one type as numpy is optimised to do array operations
- Lists can include different variable types. In this eg, '1' and 'A' have inverted commas shown 

## Accessing data in arrays and list

In [74]:
py_list_2d[0][1] #if u want to get 'A' 

'A'

In [75]:
np_array_2d[0,1] #np can access via 0,1 

np.str_('A')

## Dictionaries 

dictionaries have key pair values. The key is the actor's name, while the character name is the value. 
The value can also be a list

In [123]:
superhero_info = {
    "Natasha Romanoff": ["Black Widow", "Joannsson"],
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

In [124]:
# Accessing dictionary 

superhero_info['Natasha Romanoff']

['Black Widow', 'Joannsson']

In [125]:
# Accessing dictionary 

superhero_info['Natasha Romanoff'][1]

'Joannsson'

## 1.1 Let’s compare

## 1.2 Accessing data from a list (or array)

In [126]:
py_list=["
    a1", #0
    "b2", #1
    "c3", #2
    "d4", #3
    "e5", #4
    "f6", #5
    "g7", #6
    "h8", #7
    "i9", #8
    "j10"] #9
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

SyntaxError: unterminated string literal (detected at line 1) (1280089116.py, line 1)

In [127]:
py_list[3:6] #this will print #3,4,5. It will not print g7 due to pythons indexing 

['d4', 'e5', 'f6']

In [128]:
py_list[3:] #this will print everything from 3 onwards

['d4', 'e5', 'f6', 'g7', 'h8', 'i9', 'j10']

In [129]:
py_list[3:6:2] #this will start at 3, end at 6, select every second element from the range

['d4', 'f6']

In [130]:
py_list[-1::-1] # this will start at the end, end at the start, and select every 1st element from the range

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

In [131]:
py_list_2d[1:4]

[[2, 'B'], [3, 'C'], [4, 'D']]

In [132]:
np_array_2d[:,0].astype(int)**3 #can do math in numpy array

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

## Growing to lists

In [133]:
[1, 2] + [8,9,0], + ['A','B']: 

SyntaxError: invalid syntax (3075083747.py, line 1)

In [134]:
x=[1,2,3]
x[0]=10000
x

[10000, 2, 3]

In [135]:
y=(1,2,3) #this is a tuple 
y[0]=1000 

# tupples cannot be changed. but list and arrays can 

TypeError: 'tuple' object does not support item assignment

In [136]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

x, y, z

([1, 2, 3], [1, 2, 3], [1, 2, 3])

In [137]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x  

x[0] = 1000



x,y,z

([1000, 2, 3], [1000, 2, 3], [1000, 2, 3])

In [138]:
x=[1, 2, 3]
x[0] = 1000
y=x.copy()
z=x.copy()

x,y,z

([1000, 2, 3], [1000, 2, 3], [1000, 2, 3])

## 1.4 Higher dimensional lists

# 2 Lists vs. Arrays

## 2.1 Size

## 2.2 Arrays are fussy about type

## 2.3 Adding a number

## 2.4 Adding another list

## 2.5 Multiplying by a Number

## 2.6 Squaring

## 2.7 Asking questions

## 2.8 Mathematics

## Footnotes